config/routes.rb
Rails.application.routes.draw do
  root 'breeds#index'
  post 'fetch_breed', to: 'breeds#fetch_breed'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  require 'net/http'

  def index
  end

  def fetch_breed
    breed = params[:breed]
    url = URI("https://dog.ceo/api/breed/#{breed}/images/random")
    response = Net::HTTP.get(url)
    result = JSON.parse(response)

    if result['status'] == 'success'
      @breed = breed
      @image_url = result['message']
    else
      @error = "Breed not found"
    end

    respond_to do |format|
      format.html { render partial: 'breed_result' }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/views/breeds/_breed_result.html.erb
<% if @error %>
  <p><%= @error %></p>
<% else %>
  <h3><%= @breed %></h3>
  <img src="<%= @image_url %>" class="img-fluid" />
<% end %>

app/views/breeds/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= form_with url: fetch_breed_path, method: :post, data: { turbo_frame: "breed_result" } do |form| %>
        <div class="form-group">
          <%= form.label :breed, 'Breed' %>
          <%= form.text_field :breed, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= form.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <%= turbo_frame_tag "breed_result" do %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogbreedApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>